# Generated by Django 5.1.2 on 2024-10-11 05:13

import django.db.models.deletion
import django.utils.timezone
import uuid_extensions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("published_at", models.DateTimeField(null=True, blank=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="stories", to="art.tag", blank=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("markdown", models.TextField()),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="art.story",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("story", "index"), name="chapter__unique__story__index"
            ),
        ),
    ]
