# Generated by Django 5.1.4 on 2025-01-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art", "0002_postgres_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="synopsis",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chapter",
            name="synopsis",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
