# Generated by Django 5.1.4 on 2024-12-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art", "0002_postgres_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="is_nsfw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(default="", blank=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="pretty_name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
