version: 2.1
orbs:
  codecov: codecov/codecov@5.0.0
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_latest:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
      - build_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test
      - lint
jobs:
  build_latest:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: >
            docker build
            -t henhouse_server:latest
            --progress=plain
            --build-arg BUILD_ENV=production
            .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag henhouse_server:latest $DOCKER_USERNAME/henhouse_server:latest
            docker push $DOCKER_USERNAME/henhouse_server:latest

  build_tag:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: >
            docker build
            -t henhouse_server:latest
            --progress=plain
            --build-arg BUILD_ENV=production
            .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag henhouse_server:latest $DOCKER_USERNAME/henhouse_server:$CIRCLE_TAG
            docker push $DOCKER_USERNAME/henhouse_server:$CIRCLE_TAG

  test:
    docker:
      - image: cimg/python:3.13
        environment:
          PIPENV_VERBOSITY: -1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: Python test
          command: python --version
      - run:
          name: pipenv setup
          command: |
            pip install -U pip
            pip install -U pipenv
      - run:
          name: pipenv install
          command: pipenv sync --dev
      - save_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs/"
            - "~/.pyenv/"
      - run:
          name: Test
          command: pipenv run coverage run manage.py test
      - run:
          name: Generate Coverage XML
          command: pipenv run coverage xml
      - codecov/upload

  lint:
    docker:
      - image: cimg/python:3.13
        environment:
          PIPENV_VERBOSITY: -1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: Python test
          command: python --version
      - run:
          name: pipenv setup
          command: |
            pip install -U pip
            pip install -U pipenv
      - run:
          name: pipenv install
          command: pipenv sync --dev
      - save_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs/"
            - "~/.pyenv/"
      - run:
          name: ruff lint
          command: pipenv run ruff check .
      - run:
          name: ruff format
          command: pipenv run ruff format --check .
