# Generated by Django 5.1.2 on 2024-10-23 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app_admin.models


class Migration(migrations.Migration):
    dependencies = [
        ("app_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "key",
                    models.CharField(
                        default=app_admin.models.generate_token_key,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(null=True, blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
